path_login.go
path_login_test.go
path_role.go
path_role_test.go

Fixes #9 
This isn't finished, putting here for the moment to get some early feedback.

Allow specifying delimiters to access group information in nested claims

---

path_config.go
path_config_test.go
path_login.go

By default, only RS256 is supported.  We use RS512 for our JWT service, so we'd prefer to default to both being available.

Allow configuration of supported signing algorithms

---

claims.go
claims_test.go
path_login.go
path_login_test.go
path_oidc.go
path_oidc_test.go
scripts/local_dev.sh

- verify bound_claims in all paths
- verify bound_claims against /userinfo data
- verify bound_audiences in all paths
- revise bound_audiences check when using static keys to conform to our docs
- more tests
Fixes #30

Improve claims verification

---

cli.go

Escape URL in CLI helper on Windows

---

path_login.go
path_login_test.go

Vault must not accept signed JWT tokens through /login path when role
has role_type oidc, since there might be a situation when the client
secret could be compromised, and thus the malicious might be able to
illegitimately get a token with the right aud claim, which Vault would
accept through the /login path.

Disable /login path for roles with role_type oidc

---

backend.go
path_config.go
path_login.go
path_oidc.go
path_oidc_test.go
scripts/local_dev.sh

Use configured TLS certs for OIDC operations

---

cli.go

The lifecycle of this listener is relatively short and it should be cleanup by the end of the CLI call as the program exits, but it wouldn't hurt to be explicitly calling `listener.Close()` when we're done serving.

explicitly close the listener

---

go.mod
go.sum
vendor/github.com/mitchellh/pointerstructure/LICENSE
vendor/modules.txt

github.com/mitchellh/pointerstructure was updated to include a license. This PR just updates the module and re-vendors the package now complete with the LICENSE file.

Update pointerstructure module

---

backend.go
path_config.go
path_config_test.go
path_login.go
path_login_test.go
path_oidc.go
path_oidc_test.go
path_role.go
path_role_test.go

Add JWKS support

---

claims.go
claims_test.go

If a list of claims is provided, unmarshal it and then search within that for the bound claim.
The intention is to allow me to pass a claim like:
```vault_role: ["admin", "superadmin"]```
This will allow me to log in as either `admin` or `superadmin` as I choose.
Useful for testing roles that other users have, or to allow people who sit across two teams to perform functions in both without adding additional roles.

Add functionality to check against a list of claims

---

path_login.go
path_login_test.go
path_oidc_test.go

This check was incorrectly removed for OIDC roles in https://github.com/hashicorp/vault-plugin-auth-jwt/pull/38.
The PR also includes a test for this case and some general test cleanup.

Restore client_id check

---

claims.go
claims_test.go
path_login.go
path_login_test.go

This also refactors a crazy long test function signature into
a config structure.
Fixes #62

Convert a single string groups claim into a list of one

---

path_login_test.go
path_oidc.go
path_oidc_test.go

This PR also reduces the chance of "too many open files" errors during
tests by closing httptest servers.
Fixes #66

Add common token fields to OIDC login response

---

claims.go
claims_test.go

The current implementation only supports strings and lists when cross-checking claim bounds. This change will allow boolean k-v items to be verified.
Standard claims can be of boolean type as per: https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

Add support for boolean values in bound claims 

---

cli.go

Solves https://github.com/hashicorp/vault-plugin-auth-jwt/issues/79
* allow for setting `http` or `https` method in `redirect_uri`
* allow for setting port in `redirect_uri`
* updated plugin help info

more customisation for callback URL

---

cli.go

This addresses the issue raised in #85 in a way that should allow flexibility for users of the options added in #80.

Default OIDC callback listener to only listen on localhost

---

claims.go
claims_test.go
go.mod
path_login.go
path_oidc.go
path_role.go
path_role_test.go

This merge request is intended to add the ability to match bound claims not only using an exact string matching, but also a mathcing based on regular expressions.
Added a new flag `bound_claims_are_regexps`; if it is set to true the vaule of each entry in the `bound_claims` map is expected to be a string (not an array of strings) that will be interpreted as a regular expresison. The syntax for the regular expressions is the golang syntax.
This would allow mathcing JWT whose claims, for example, contain randomly generated portions of text.
Solves issue https://github.com/hashicorp/vault-plugin-auth-jwt/issues/82

Add the ability to match bound claims using globs

---

path_role_test.go

Moved a bunch of tests in large test functions into their own sub tests using `t.Run`. This helps prevent test bleedover effects, makes the test output easier to read, and makes the tests easier to debug.

Move tests into sub tests

---

cli.go

We've seen some users initiate a Vault login using the OIDC method via the Vault CLI (`vault login -method=oidc`) and become distracted mid login and not complete the OIDC flow in their browser. 
When they attempt later to log in from another terminal tab or window using `vault login -method=oidc`, they received the error `listen tcp :8250: bind: address already in use` because the callback server from the initial login call is still running in a terminal somewhere.
This pull request adds a 2 minute timeout to the callback server to avoid zombie callback servers sticking around on a user's machine potentially indefinitely. I picked 2 minutes mostly arbitrarily based on how long I thought it usually takes me to do a login to an OIDC provider (including both password entry and 2FA second …

Add timeout to OIDC callback server listener

---

path_config.go

`role` is already TypeLowerCaseString, and currently if `default_role` is
mixed case it will never match `role`.
This change only affects new configurations.

Change default_role to be lowercase

---

cli.go
path_oidc.go
path_oidc_test.go

This optional nonce hardens the multi-step OIDC login process. If the
client provides a nonce at the start (auth_url) phase, it must provide
the same nonce as part of the callback.
The motivation for this is primarily CLI logins. The CLI listener is
necessarily unencrypted, and theoretically if an attacker stole the OAuth
authorization_code enroute to the CLI listener, it could post that to
Vault and gain access. The CLI leverages the new client_nonce support to
harden this flow. Only the CLI process (and Vault) will know the
client_nonce, so an attacker will be unable to complete the login even
if they manage to steal the authorization_code.

Add optional client_nonce for OIDC logins

---

path_oidc.go

Moves the `/auth_url` error message for non-OIDC flows into the constants section containing error messages used in the Vault UI.
This change was primarily done in the Vault UI. See related PR below for full explanation.
- [PR #8952](https://github.com/hashicorp/vault/pull/8952)

Moves auth_url error message for non-OIDC flow into ui constants

---

path_config.go

Backport of #129 into `release/vault-1.5.x`

Backport 1.5.x; adding EdDSA (ed25519) to supported algorithms (#129)

---

path_config.go

Remove provider_config DisplayAttrs.Value, since that is treated as the default by the UI, and the default should
be empty. This was causing issues with the UI.

Remove provider_config DisplayAttrs.Value

---

cli.go

When using a custom allowed_redirect_uris for specific roles
we don't show a relationship between the role and the
redirect_uri when an authorization error occurred,
frustrating the user thinking that the problem is in
the role and not in the allowed_redirect_uris flag.
This error is common occurred with the CLI when the administrator doesn't add an allowed localhost path.

Improve authorization error

---

path_config.go
path_config_test.go
path_oidc.go
path_oidc_test.go

Add an option to the OIDC config to pass namespace in the state parameter instead of as a separate query parameter. With this setting the allowed redirect URL in Vault and on the provider side should not contain a namespace query parameter. This means only one redirect URL entry needs to be maintained on the provider side for all vault namespaces that will be authenticating against it.
To test this, I've been doing something like this along with the vault PR https://github.com/hashicorp/vault/pull/10171:
- `yarn start` in the vault/ui directory to start the UI in live-reloading/dev mode
- `./scripts/local_dev.sh` in this vault-plugin-auth-jwt repo, with a vault enterprise binary in your path
- visit the UI at http://localhost:4200/
A config option in the OIDC config
<details>
```
❯ make …
```

Adds OIDC namespace_in_state option

---

path_config.go
path_login.go
path_oidc.go
provider_azure.go
provider_azure_test.go
provider_config.go
provider_config_test.go
provider_gsuite.go
provider_gsuite_test.go

This PR fixes https://github.com/hashicorp/vault-plugin-auth-jwt/issues/138 by validating the `bound_claims` of a role after the provider-specific group and user info fetching. This allows usage of `bound_claims` for validation against additional group membership and user information on a role. 
I've added an automated test which ensures that groups and user info claims can be validated using `bound_claims`.
Additionally, I've manually tested that `bound_claims` validation works against a G Suite account with both groups and user custom schema data.
See test output below with comments explaining the expected results:
```bash
$ vault auth enable oidc
Success! Enabled oidc auth method at: oidc/
$ vault write auth/oidc/config -<<EOF
{
"oidc_discovery_url": "https://accounts.google.com", …
```

Fixes bound_claims validation for provider-specific group and user info fetching

---

path_config.go
path_login.go
path_oidc.go
provider_azure.go
provider_azure_test.go
provider_config.go
provider_config_test.go
provider_gsuite.go
provider_gsuite_test.go

This PR backports a bug fix from #149.
1. `git checkout release/vault-1.6.x`
2. `git checkout -b backport-pr-149-1.6.1`
3. `git cherry-pick c1176c2`

Backport 1.6.1: fixes bound_claims validation for provider-specific group and user info fetching (#149)

---

path_oidc.go

The intent of this debug logging is to help understand the structure of the received token. The signature isn't needed for this so let's log the minimum required information.

Strip signature from debug-logged token

---

path_oidc.go
path_oidc_test.go
path_role.go
path_role_test.go

This PR adds a new `max_age` parameter to roles. The `max_age` specifies the allowable elapsed time in seconds since the last time the user actively authenticated with the configured identity provider. 
When `max_age` is used, the ID Token returned must include an `auth_time` claim value (see [openid-connect-core-1_0.html#AuthRequest](https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest)). Validation of the `auth_time` claim value is provided by the cap/oidc library (see [oidc/provider.go#L414](https://github.com/hashicorp/cap/blob/main/oidc/provider.go#L414)).
The `max_age` for a role will be included in the generated auth URL as a query parameter, similar to the following example:
```
https://example.auth0.com/authorize?client_id=abc&max_age=60&nonce=n_NEJOgEMl4MBXf0LX6ES4&r …
```

Adds max_age role parameter and auth_time claim validation

---

path_login.go
path_login_test.go

This PR changes the handling of `jwt_supported_algs` to be consistent with the behavior prior to PR https://github.com/hashicorp/vault-plugin-auth-jwt/pull/155. This means that `jwt_supported_algs` will remain optional and default to the set of algorithms defined in [jwt/algs.go#L12-L21](https://github.com/hashicorp/cap/blob/main/jwt/algs.go#L12-L21) for JWT based authentication.
A default of `RS256` is still used for OIDC based authentication.
I've tested that JWT auth works without needing to always provide the correct signing algorithm via `jwt_supported_algs` for both JWKS and static key configurations.

Validate JWT supported algorithms against supported set if not provided in config

---

path_config.go
provider_gsuite.go
provider_gsuite_test.go

This PR enables the [gsuite_service_account](https://www.vaultproject.io/docs/auth/jwt_oidc_providers#gsuite_service_account) to be directly provided as a JSON string in the G Suite provider config. This is similar to how credentials are provided in the GCP [secrets](https://www.vaultproject.io/api-docs/secret/gcp#credentials) and [auth](https://www.vaultproject.io/api-docs/auth/gcp#credentials) plugins. To remain backward compatible, the credentials may still be provided as a path to a service account file on the host that the plugin is running on.
This PR also implements the [SensitiveKeys](https://github.com/hashicorp/vault-plugin-auth-jwt/blob/master/provider_config.go#L29-L31) behavior for custom providers. This is used to omit sensitive configuration (e.g., raw service account …

Adds ability to directly provide service account JSON in G Suite provider config

---

path_config.go
provider_gsuite.go
provider_gsuite_test.go

This PR backports an enhancement from #167 to the 1.7.x release branch.
2. `git checkout -b backport-pr-167-1.7.x`
3. `git cherry-pick f8f6db6`

Backport 1.7.x: Adds ability to directly provide service account JSON in G Suite provider config (#167)

---

cli_responses.go

This PR backports a bug fix from #174.
1. `git checkout release/vault-1.8.x`
2. `git checkout -b backport-pr-174-1.8.x`
3. `git cherry-pick 7311fc7f94c5e2d3b32ebc2824b61a782e03edf3`

Backport 1.8.x: Fixes form_post response mode scripting for browser (#174)

---

cli_responses.go

This PR backports a bug fix from #174.
1. `git checkout release/vault-1.6.x`
2. `git checkout -b backport-pr-174-1.6.x`
3. `git cherry-pick 7311fc7f94c5e2d3b32ebc2824b61a782e03edf3`

Backport 1.6.x: Fixes form_post response mode scripting for browser (#174)

---

cli_responses.go

This PR backports a bug fix from #174.
2. `git checkout -b backport-pr-174-1.7.x`
3. `git cherry-pick 7311fc7f94c5e2d3b32ebc2824b61a782e03edf3`

Backport 1.7.x: Fixes form_post response mode scripting for browser (#174)

---

path_oidc.go
path_oidc_test.go

Add PKCE to OIDC Auth
use the cap library to set the pkce option
[x] Add relevant docs to upstream Vault repository, or sufficient reasoning why docs won’t be added yet
[x] Add output for any tests not ran in CI to the PR description (eg, acceptance tests)
[x] Backwards compatible
<details>
<summary>Tests</summary>
```
$ make test
VAULT_ACC=1 go test -tags='vault-plugin-auth-jwt' $(go list ./... | grep -v /vendor/) -v  -timeout 10m
=== RUN   TestGetClaim
--- PASS: TestGetClaim (0.00s)
=== RUN   TestExtractMetadata
--- PASS: TestExtractMetadata (0.00s)
=== RUN   TestValidateAudience
--- PASS: TestValidateAudience (0.00s)
=== RUN   TestValidateBoundClaims
--- PASS: TestValidateBoundClaims (0.00s)
=== RUN   Test_normalizeList
--- PASS: Test_normalizeList (0.00s)
=== RUN   TestParseHelp
=== …
```

Add PKCE to OIDC Auth

---

path_oidc.go
path_oidc_test.go

This PR backports #188 
1. `git checkout release/vault-1.9.x`
2. `git checkout -b backport-pr-188-1.9.x`
3. `git cherry-pick 7010da264993747d78ec4fab83505abab0b97c25`

Backport 1.9.x: Add PKCE to OIDC Auth (#188)

---

cli_responses.go

This PR fixes a regression introduced in Vault 1.9.1 that caused the implicit flow (`oidc_response_types=id_token`) to no longer work from the Vault UI. The cause of the regression was https://github.com/hashicorp/vault/pull/13133, which added a required `source` field to the data sent via `postMessage` between the window objects.
Fixes https://github.com/hashicorp/vault/issues/13460.
I tested that this fixes the implicit flow using Azure AD from the Vault UI.

Fixes UI for implicit flow by adding required source to postMessage

---

cli_responses.go

This PR backports #192.
Steps:
1. `git checkout release/vault-1.9.x`
2. `git checkout -b backport-pr-192-1.9.x`
3. `git cherry-pick 6bd8f3169efdcc0f2f9ea1264e8182026c8c9bb1`

Backport 1.9.x: Adds UI postMessage source required for implicit flow (#192)

---

cli_responses.go

This PR backports #192.
Steps:
1. `git checkout release/vault-1.8.x`
2. `git checkout -b backport-pr-192-1.8.x`
3. `git cherry-pick 6bd8f3169efdcc0f2f9ea1264e8182026c8c9bb1`

Backport 1.8.x: Adds UI postMessage source required for implicit flow (#192)

---

cli_responses.go

This PR backports #192.
Steps:
2. `git checkout -b backport-pr-192-1.7.x`
3. `git cherry-pick 6bd8f3169efdcc0f2f9ea1264e8182026c8c9bb1`

Backport 1.7.x: Adds UI postMessage source required for implicit flow (#192)

---

path_role.go

A high level description of the contribution, including:
A simple bug fix. The /role/ path doesn't return success because we get an empty secret interface returned instead of nil. To fix this we just return nil,nil when no warnings are present.
Who the change affects or is for (stakeholders)?
This affects those who are programmatically checking the cli commands to see if roles were successfully written. 
What is the change? 
return nil,nil when no warnings are present when creating roles
Why is the change needed?
So, users can know whether their roles were successfully written to vault
How does this change affect the user experience (if at all)?
Users won't know if their roles were successfully written. If they want to programmatically check for it, they need to list all roles. 
How was …

Return nil if no warnings when creating roles

---

provider_azure.go

The azure provider has some code to correctly identify and convert the Azure AD Graph host to the MS Graph host. For reasons unknown to me, Microsoft will not update the JWT to correctly send MS Graph URLs even though AD Graph is deprecated.
This PR extends the current conversion to support the US Gov cloud offering (https://docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-request-differences)

Azure provider - Add Support for US Gov L4 

---

cli.go

In order to make `CLIHandler.Auth()` work in a fully non-interactive context, i.e. from the Terraform Vault Provider, it needs to be able to abort on any error encountered. This PR adds support for a new parameter `abort_on_error` to control the new behavior.
[ ] [Issue #1234](https://github.com/hashicorp/vault/issues/1234)
[ ] [PR #1234](https://github.com/hashicorp/vault/pr/1234)
[ ] Add relevant docs to upstream Vault repository, or sufficient reasoning why docs won’t be added yet
[X] Backwards compatible

Update CLIHandler.Auth() to support aborting on any error

---

CHANGELOG.md
provider_gsuite.go
provider_gsuite_test.go

This PR adds the ability to set the Google workspace domain for groups search.
Addresses https://github.com/hashicorp/vault-plugin-auth-jwt/issues/216.
- https://github.com/hashicorp/vault-plugin-auth-jwt/issues/216
- Will add docs

Adds ability to set Google workspace domain for groups search

---

CHANGELOG.md
README.md
cmd/vault-plugin-auth-jwt/main.go
go.mod
go.sum

- the plugin will be multiplexed when run as an external plugin against vault versions that support plugin multiplexing
- we continue to set the TLSProviderFunc to maintain backwards compatibility with vault versions that don't support AutoMTLS (< 1.12)

enable plugin multiplexing

---

provider_gsuite.go
provider_gsuite_test.go

This commit adds support for authenticating to the Google Workspace Directory API through [Application Default Credentials](https://cloud.google.com/docs/authentication/application-default-credentials). ADC is assumed if `ServiceAccount` is left empty.
Authentication can be performed through domain-wide delegation of authority by impersonating a workspace user, or directly by granting the service account the necessary admin roles.
See the [docs](https://cloud.google.com/identity/docs/how-to/setup#auth-no-dwd) for authenticating as a service account without domain-wide delegation of authority.
This commit introduces a new config field,`ImpersonatePrincipal`. This field is used as a target service account to create a signed JWT for the Workspace user to impersonate. This is useful in a …

Support ADC for Google Workspace (dwd/no-dwd)

---

path_oidc.go

As described in hashicorp/vault#21949 endpoints with non-path parameters
that can be made use of during ReadOperation callbacks should have those
fields marked as `Query: true` to ensure the OpenAPI spec truly reflects
how the endpoints can be called.
This should also provide a proper fix to hashicorp/vault-client-go#155.
I'm also changing the operation ID to reflect that GET and POST on
`oidc/callback` are **not** at all the same operation with and without
parameters, but in fact play substantially different roles in the
overall OIDC login flow.

Add missing `Query: true` metadata to API definitions

---

cli.go

If a CLI user issues a stop signal (SIGTSTP usually via Ctrl-Z) instead of an interrupt signal (SIGINT usually via Ctrl-C), the process will indefinitely hold the OIDC callback listener port until the process is forcibly killed or the process is resumed and the timeout is achieved.
Most users won't notice these changes or they will never have experienced this because: 1) they are running this locally without `skip_browser=true` or 2) they're not working in a shared environment. There are other areas where this issue could arise, but these are the most common. This change is mainly for system administrators so that the port cannot be unintentionally held by a user issuing the incorrect command to stop the login flow.
This change closes the listener when a SIGTSTP signal is received. …

Close HTTP listener if stop signal received

---

path_login.go
path_login_test.go
path_oidc.go
path_oidc_test.go

This PR is suggesting the addition of the `role` name in the Entity Alias metadata on successful login.
**Adding the role name on the Entity Alias metadata makes it easier to manage access to endpoints via [ACL templated policies](https://learn.hashicorp.com/tutorials/vault/policy-templating#step-1-write-templated-acl-policies). Using the plugin mount accessor, one can simply use the following rule to restrict access: `identity.entity.aliases.<mount_accessor>.metadata.role`**. Another auth plugin, AppRole, recently implemented this change for the same reason: https://github.com/hashicorp/vault/pull/9529
Also, it already seems like the authors of _this_ plugin had in mind that `role` is an important metadata that should not be overriden. We can assume this from the following two things. …

Include role name in Entity Alias metadata

---

cmd/vault-plugin-auth-jwt/main.go

Add missing error check to `main()` for parsing CLI flags. If `flags.Parse()` fails now the error is hidden from the user.
An error check was missing and I added it 👍
Originally noticed at https://github.com/hashicorp/vault-plugin-auth-kubernetes/pull/202
[-] Add relevant docs to upstream Vault repository, or sufficient reasoning why docs won’t be added yet
Not needed
[-] Add output for any tests not ran in CI to the PR description (eg, acceptance tests)
Not needed
[x] Backwards compatible

chore: add errcheck for parsing cli flags

---

CHANGELOG.md

This PR adds a changelog entry for the [v0.18.0](https://github.com/hashicorp/vault-plugin-auth-jwt/releases/tag/v0.18.0) release of this plugin.

v0.18.0: adds changelog entry

---

CHANGELOG.md
claims.go
claims_test.go
path_login_test.go

The OIDC/JWT plugin does not support `bound_claims` other than strings or bools: https://github.com/hashicorp/vault-plugin-auth-jwt/blob/main/claims.go#L130. However, I encountered a JWT, which contains a numeric claim, which I want to bind to. 
I think it makes sense to support numeric bound claims - in fact, this was the original idea laid out in this comment: https://github.com/hashicorp/vault-plugin-auth-jwt/pull/24/files#r256926892
We are adding support for numeric claims in `bound_claims`.
None
[X] Add relevant docs to upstream Vault repository, or sufficient reasoning why docs won’t be added yet
No changes are needed in the documentation since it doesn't go into the details of what is/not supported in the bound claims.
[ ] Add output for any tests not ran in CI to the PR …

Support numeric claims

---

CHANGELOG.md

This PR adds a changelog entry for the [v0.19.0](https://github.com/hashicorp/vault-plugin-auth-jwt/releases/tag/v0.19.0) release of the plugin.

Adds changelog entry for v0.19.0

---

path_oidc.go
path_oidc_test.go

This PR proposes to make the redirecut URI matching validation case-insensitive.
An HVD user recently reported an issue where they could not log into the Vault UI using the OIDC auth method even when the URL was correct. 
```
"Error: Missing auth_url. Please check that allowed_redirect_uris for the role include this mount path."
```
This was discovered when a customer had named their HVD cluster with capital letters (e.g. ABC-cluster).  
When setting allowed_redirect_uris as a part of the [OIDC setup process](https://developer.hashicorp.com/vault/tutorials/auth-methods/oidc-auth?in=vault%2Fauth-methods#get-auth0-credentials) and then attempting to login to the Vault UI, the browser automatically transforms the login URL to all-lowercase, causing the URL to not match the configured …

make redirect uri validation case-insensitve

---

CHANGELOG.md
go.mod
go.sum
path_login.go
path_login_test.go
path_oidc_test.go
path_role.go

Our JWT invalidation on empty bound audiences currently includes only the non-empty string array "aud" case. However, https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3 states 
> In the special case when the JWT has one audience, the "aud" value MAY be a single case-sensitive string containing a StringOrURI value.
- Inspired from https://github.com/hashicorp/vault-plugin-auth-jwt/commit/6adc3db3d7d05232bc627afd1857e5fb6d21328d, invalidation of JWT with single non-empty string "aud" is applied on empty bound audiences.
- http://github.com/go-jose/go-jose/v3 (+/jwt) replaces [go-jose.v2 - gopkg.in/square/go-jose.v2](http://gopkg.in/square/go-jose.v2) (+/jwt) in `path_login_test.go` and `path_oidc_test.go` to allow "aud" to take the single case-sensitive string form when it is one …

invalidate JWT with single non-empty string aud on empty bound audiences

---

CHANGELOG.md
path_login_test.go

This is a no-op release to be imported into Vault 1.17.x. We are doing this for 2 reasons in order of priority:
1. We need to revert https://github.com/hashicorp/vault-plugin-auth-jwt/pull/295 on the plugin's v0.20.x release but we want to keep that change going forward.
2. Currently, Vault 1.16.x and 1.17.x bundle the same plugin minor version which is not ideal because it can make backporting difficult.

Prepare for v0.21.0 release

---

path_login_test.go

This test was copied from https://github.com/hashicorp/vault-plugin-auth-jwt/pull/308 and modified to match the new behavior. However, the comment was not updated. This PR corrects the commend to match the behavior.

update incorrect test comment

---

path_role.go
path_role_test.go

This PR allows users to optionally ignore the trailing slash at the end of each bound audience (if the trailing slash exists) by setting the `bound_audience_disregard_trailing_slash` flag to `true`. The PR also prevents duplicate bound_audiences from being entered, where the only difference would be the trailing slash (ie adding `https://testing.com` and `https://testing.com/` to the `bound_audiences` field results in `https://testing.com` being the only one added when the flag is in place. The default behavior remains in place if the flag is not set to true.
* Created API on Auth0 with audience of `https://testing.com`
* Enable JWT in Vault
```vault auth enable jwt```
* Config JWT
```
vault write auth/jwt/config \
oidc_discovery_url="https://MY_DOMAIN.us.auth0.com/" \
oidc_client_id="" \ …
```

Optionally Ignore trailing "/" at end of boundAudience

---

CHANGELOG.md

Updating the changelog for the changes in https://github.com/hashicorp/vault-plugin-auth-jwt/pull/329 and subsequent backports. Included direct dependency updates.

update changelog for recent releases

---

CHANGELOG.md
go.mod

update go mod to 1.24. this is so the go version in go.mod is the same as Vault's
Stage for 0.24.1 release for this update to go.mod

set go.mod to 1.24
