- .gitignore
- backend.go
- claims.go
- claims_test.go
- path_login.go
- path_login_test.go
Implements code style tweaks from #21.
> Minor code style tweaks

- cli.go
- path_role_test.go
> Change default CLI port to 8250

- cli.go
Fixes https://github.com/hashicorp/vault/issues/6921
> Don't panic in CLI on nil auth URL response

- go.mod
- go.sum
- path_login.go
- path_login_test.go
- path_role.go
- path_role_test.go
Converting the custom leeway parameters to use the new `TypeSignedDurationSecond` type to support disabling leeway.
> Change leeways to TypeSignedDurationSecond

- path_oidc.go
Addresses `expired/missing oauth state` errors
> Forward OIDC logins received on performance standbys

- cli.go
Add a parameter to change the hostname in the url callback
Its usefull to use oidc on a remote server.
> add parameter callbackhost

- cli.go
This is a solution for Issue #76
> Issue 76: Vault login for WSL - Hardened openURL function for WSL

- path_config.go
This PR adds EdDSA to the list of supported algorithms in the library. The underlying library already supports this implementation.
> Adding EdDSA (ed25519) to supported algorithms

- path_config.go
> Backport Remove provider_config DisplayAttrs.Value #141

- CHANGELOG.md
This PR adds a CHANGELOG.md to keep a historical record of upcoming bug fixes, features, and improvements. It also lets us track and bundle up multiple PR merges into a single release to update back into Vault without having to issue a patch release on every merge.
> Adds changelog file

- path_login.go
- path_login_test.go
This PR backports a behavior fix from #161.
2. `git checkout -b backport-pr-161-1.7.x`
3. `git cherry-pick e8af984`
> Backport 1.7.x: Validate JWT supported algorithms against supported set if not provided in config (#161)

- path_oidc.go
- path_oidc_test.go
This PR fixes a panic that occurs when an implicit flow is requested. An implicit flow is requested when [oidc_response_types](https://www.vaultproject.io/api-docs/auth/jwt#oidc_response_types)=`id_token` and [oidc_response_mode](https://www.vaultproject.io/api-docs/auth/jwt#oidc_response_mode)=`form_post`. It fixes the panic by adding a `nil` check around token access. See the related issue for more details: https://github.com/hashicorp/vault/issues/11125.
This PR additionally adds an ID token verification step for the implicit flow, which was missing since adopting the cap library.
I was able to successfully reproduce the stack trace and panic from the linked issue using Azure as an identity provider. I manually tested that the panic no longer occurs using the changes in this PR.
I also …
> Fixes a panic that occurs when an implicit flow is requested

- path_oidc.go
- path_oidc_test.go
This PR backports a bug fix from #163 to the 1.7.x release branch.
2. `git checkout -b backport-pr-163-1.7.x`
3. `git cherry-pick 7d42b61`
> Backport 1.7.x: Fixes a panic that occurs when an implicit flow is requested (#163)

- CHANGELOG.md
Added a changelog entry for the fix merged in #251 to prepare a patch release.
> Changelog for 1.17.1 release

- CHANGELOG.md
> update changelog for 0.17.2

- CHANGELOG.md
This PR updates the changelog for the v0.20.0 release.
> Prepare for v0.20.0 release

- go.mod
- go.sum
Need to get past security scanner to release v0.20.1
> update protobuf dependency to fix cve

- CHANGELOG.md
This PR updates the changelog for the v0.20.3 release.
> prepare for v0.20.3 release

- path_login.go
This PR backports https://github.com/hashicorp/vault-plugin-auth-jwt/pull/329 into version 1.18.x.
> Vault 34298 backport auth group sourcing 1.19.x

- CHANGELOG.md
Changelog update for version [v0.25.0](https://github.com/hashicorp/vault-plugin-auth-jwt/releases/tag/v0.25.0).
---
_This PR was generated by an automated workflow._
Full log: https://github.com/hashicorp/vault-plugin-release/actions/runs/18213847668
> [CHANGELOG] Prepare for v0.25.0 release
